Add Homework11
DaryaZyubina/iosSchool pull request #11
Opened 2023-04-30 20:16 UTC by DaryaZyubina

2023-05-01 06:45 UTC, vaganova-ann requested changes
Все обращения к UserDefaults делать только в StorageManager

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/ApiClient/ProfileApiClient.swift
> +        let id = profileId ?? ""
может не будем выполнять запрос, если profileId == nil?

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/AppCoordinator.swift
> +            UserDefaults.standard.set(Date(), forKey: userId)
дебажные принты убираем
для работы с UserDefaults на занятии завели менеджера, в нем заводим новые функции и пользуемся ими

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/AppDelegate.swift
> +        //assembly.storageManager.cleanKeychainIfNeeded()
почему закомментировала? почему removeToken на входе? пользователи не любят заходить в приложение и выяснять, что им нужно опять логиниться

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/Auth/AuthAssembly.swift
> +        .init(dataProvider: authDataProvider(), profileDataProvider: profileDataProvider(), storageManager: storageManager, onLoginSuccess: onLoginSuccess)
ворнинг

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +    init(dataProvider: AuthDataProvider, profileDataProvider: ProfileDataProvider, storageManager: StorageManager, onLoginSuccess: (() -> Void)?) {
ворнинг

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +                UserDefaults.standard.set(Date(), forKey: "TimeWithToken:\(userId)")
используем менеджер

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +                    print(profileResult)
принт убираем

2023-05-01 06:45 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +                self?.profileDataProvider.getProfile(profileId: userId) { profileResult in
weak self потеряла, можно вынести profileDataProvider.getProfile(profileId: userId) в функцию, чтобы было нагляднее

2023-05-01 13:29 UTC, DaryaZyubina commented on iosSchool/AppDelegate.swift
> +        //assembly.storageManager.cleanKeychainIfNeeded()
Не подобрала "хвосты" после тестирования :(

2023-05-01 14:17 UTC, vaganova-ann requested changes
Давай еще добавим для регистрации запрос данных пользователя и сохранение даты последнего входа, там же флоу успешной регистрации анологично флоу успешной авторизации

2023-05-01 14:17 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
>                          DispatchQueue.main.async {
мне кажется здесь не надо показывать ошибку пользователя, он же с этим ничего не может сделать

2023-05-01 14:17 UTC, vaganova-ann commented on iosSchool/Auth/AuthViewController.swift
> +                        self?.storageManager.setUsernameToProfile(profile: profile, defaultName: "Bob")
за дефолтное имя должна отвечать вью модель в модуле профиля, если тебе понадобится настраивать дополнительно дефолтное имя, то ты будешь по всему приложению фиксить вместо одного места

2023-05-01 14:17 UTC, vaganova-ann commented on iosSchool/Services/StorageManager.swift
> +        if profile.username != "" {
здесь лучше тогда не сохранять пришедшее пустое имя вообще

2023-05-02 02:53 UTC, vaganova-ann approved these changes

2023-05-05 11:31 UTC, merged