Add Homework8
DaryaZyubina/iosSchool pull request #8
Opened 2023-04-21 10:22 UTC by DaryaZyubina

2023-05-02 20:21 UTC, DaryaZyubina commented
Появились несколько вопросов во время работы над домашкой:
1. Я решила сделать одну ячейку (LabelCell) для даты и цвета, и менять текст и содержание ячейки в зависимости от номера ячейки через делегат. Но почему то в ProfileView, метод getIndexOfRow приходит НЕ пустая ячейка, но индекспас не находится. Зашла в тупик, не уверена что делать с этим.
2. Можно ли как то узнать что таблица не вмещается на экран? Идея такая: сделала пустую ячейку между логином и лейблами с заданной шириной, но при недостатке места хочу эту ширину уменьшить до 1.
P.S. Вроде бы остальное все рабочее, при принты что их надо убирать помню - они для тестирования первой проблемы, после этого почищу.

2023-05-03 12:43 UTC, vaganova-ann requested changes
По модулю Locations
1) изображение на бэкграунде не то
2) цвета шрифтов не те
3) нет синей стрелочки у каждой локации
4) когда вьюшки лежат в стеквью, то мы не добавляем к ним констрейнты, это делает сам стеквью, нам нужно только поместить внутрь него и провести настройку с помощью свойств стеквью
5) проверить констрейнт между стек вью и populationLabel
6) убрать ворнинг в LocationCell

По профилю: 
1) в HeaderCell для profileImage слишком много топ и боттом констрейнтов, топ констрейнт должен связывать profileImage и headerImage, боттом констрейнт должен связывать profileImage и супервью
2) в LabelCell не используем имадж вью для фона, вместо нее берем вью и настраиваем ее по дизайну
3) в LabelCell положить dateLabel и colorLabel в стек вью, так становится меньше констрейнтов и лучше переключение между вью

Ответы на вопросы:
1) ответила выше
2) ты можешь брать высоту экрана из UIScreen.main.frame.height и в зависимости от высоты экрана в heightForRowAt изменять высоту ячейки

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Common/BaseNavigationController.swift
> +        // navigationBar.topItem?.rightBarButtonItem = UIImage(named: "refresh")
комментарий

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Location/LocationViewController.swift
> +            self?.rootView.updateTable()
рефреш нужен для перезагрузки данных, которые мы берем из сети, перезагрузка только таблицы ничего не меняет, нужно вызывать dataProvider.allLocations()

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +protocol LabelCellDelegate: AnyObject {
делегат пишем в файле, в котором лежит класс, который будет иметь свойство делегат

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        exitButtonView.setTitle("Выйти", for: .normal)
занести все настройки exitButtonView в makeButton

exitButtonView можно переименовать в exitButton

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        //tableView.bottomAnchor.constraint(equalTo: bottomAnchor).isActive = true
комментарий

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +       // exitButtonView.topAnchor.constraint(equalTo: topAnchor).isActive = true
комментарий

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +            if
здесь и ниже неправильно расположены скобки и условия по строчкам
можно так:
if let cell = tableView.dequeueReusableCell(
    withIdentifier: LoginLabelCell.className
) as? LoginLabelCell,  let profileData {
                cell.viewModel = profileData.cell
                return cell
 }
 но не оставляем повисший if и повисшую открывающую скобку

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +                cell.backgroundColor = UIColor(named: "Lilac50")?.withAlphaComponent(1)
это настраивается в ячейке

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileView.swift
> +        case 3:
можно через запятую 
case 3, 4

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +    private var profile: ProfileCellData
здесь должна быть ProfileViewData, тк ProfileCellData это вью модель для ячеек. или нет? надо оставить либо ProfileViewData либо  ProfileCellData

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ClearCell.swift
> +
ворнинг

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ClearCell.swift
> +        // Initialization code
здесь можно задать цвет

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ClearCell.swift
> +    override func setSelected(_ selected: Bool, animated: Bool) {
можно убрать если не нужно

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/LabelCell.swift
> +        guard let cell = delegate?.getIndexOfRow(cell: self) else {
слишком сложно, проще передавать тип ячейки в ее вью модели, завести для этого енам или логическую переменную, в зависимости от нее скрывать и показывать вьюшки

2023-05-03 12:43 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/ProfileCellData.swift
> +
пустая строка

2023-05-04 14:04 UTC, vaganova-ann requested changes
1) стрелочка в location cell должна быть размером побольше, даже если на дизайне ее размер 14х12
2) в LabelCell в ксибе есть красненькое уведомление о том, что нужно настроить приоритет сжатия и растяжения, надо настроить
3) писала про ProfileViewData и ProfileCellData замечание, ничего не изменилось

2023-05-04 14:04 UTC, vaganova-ann commented on iosSchool/Location/LocationViewController.swift
> +            self?.dataProvider.allLocations() { [weak self] result in
в двух местах одинаковый вызов dataProvider.allLocations() 
DRY

2023-05-04 14:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/LabelCell.swift
> +protocol LabelCellDelegate: AnyObject {
все еще нужен делегат или уже нет?

2023-05-04 14:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/LabelCell.swift
> +    var isCellContainsDate: Bool = false
давай занесем во вью модель

2023-05-04 14:04 UTC, vaganova-ann commented on iosSchool/Profile/Subviews/LabelCell.swift
> +        switch isCellContainsDate {
а можно классический if else здесь?)

2023-05-04 15:53 UTC, DaryaZyubina commented
Исправлено все кроме одного замечания:
Возник вопрос по твоему комментарию что стоит isCellContainsDate занести во вью модель.
Подразумевается, что стоит доп. перенести эту переменную во вьюмодель чтобы она была как аргумент в update, а все остальное оставить как было? Или стоит внести как-то во вьюмодель, и убрать объявление переменной в самом классе LabelCell? Если так, то я не совсем могу додуматься как тогда менять значение этой переменной (isCellContainsDate)/передать значение этой переменной из ProfileView?

2023-05-05 03:21 UTC, vaganova-ann requested changes
А кстати, давай вместо лейбла с надписью Color засунем синюю круглую вьюшечку как в дизайне

2023-05-05 03:21 UTC, vaganova-ann commented on iosSchool/Profile/ProfileViewController.swift
> +    //private var profile: ProfileCellData
комментарий

2023-05-05 07:13 UTC, vaganova-ann approved these changes

2023-05-06 13:36 UTC, merged